### ISSUE TITLE
Fehler beim ausführen des Testskriptes

### ISSUE THREAD

**Issue by evildrummer** [ggruner/Zipatoapi#1]
Hallo,

nachdem ich alle Vorgaben bzw. Abhängigkeiten installiert habe (http://zipabox.de/connection-tracking-mit-der-zipabox/)

kommt bei mir der folgende Fehler beim Starten der Fritzhosts.py

`pi@raspberrypi:~/Downloads $ python fritzhosts.py -p "PASSWORDXYZ!"
Traceback (most recent call last):
  File "fritzhosts.py", line 171, in <module>
    _print_status(_get_cli_arguments())
  File "fritzhosts.py", line 167, in _print_status
    write_hosts_file(fh)
  File "fritzhosts.py", line 101, in write_hosts_file
    hosts = fh.get_hosts_info()
  File "fritzhosts.py", line 59, in get_hosts_info
    host = self.get_generic_host_entry(index)
  File "fritzhosts.py", line 44, in get_generic_host_entry
    result = self.action('GetGenericHostEntry', NewIndex=index)
  File "fritzhosts.py", line 32, in action
    return self.fc.call_action(SERVICE, actionname, **kwargs)
  File "/home/pi/Downloads/fritzconnection.py", line 362, in call_action
    return action.execute(**kwargs)
  File "/home/pi/Downloads/fritzconnection.py", line 126, in execute
    result = self.parse_response(response.content)
  File "/home/pi/Downloads/fritzconnection.py", line 138, in parse_response
    root = etree.fromstring(response)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:79003)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118334)
  File "src/lxml/parser.pxi", line 1736, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117014)
  File "src/lxml/parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:111258)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105102)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106810)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105664)
  File "<string>", line 11
lxml.etree.XMLSyntaxError: Input is not proper UTF-8, indicate encoding !
Bytes: 0xE4 0x73 0x74 0x65, line 11, column 25
`

Es wurde auf zwei versch. RPi´s getestet (Model 3B und 3B+).

**Comment by ggruner** [comment]
Hi evildrummer,

sorry ich habe jetzt erst deine Nachricht gesehen. Falls das Problem weiterhin besteht, probier mal bitte das folgende Kommando aus:

fritzhosts.py -i „IP_ADRESSE_DES_ROUTERS“ -u „admin“ -p "ADMIN_PASSWORD_DES_ROUTERS"

**Comment by ggruner** [comment]
Ich schließe das Ticket, da kein Feedback mehr kam.
